[workspace]
resolver = "2"
members = [
    "crates/valhall",
    "crates/valhall-backend",
    "crates/valhall-config",
    "crates/valhall-docs",
    "crates/valhall-frontend",
    "crates/valhall-index",
    "crates/valhall-renderer",
    "crates/valhall-storage",
]

[workspace.package]
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[workspace.dependencies]
valhall = { path = "crates/valhall" }
valhall-docs = { path = "crates/valhall-docs" }
valhall-frontend = { path = "crates/valhall-frontend" }
valhall-index = { path = "crates/valhall-index" }
valhall-storage = { path = "crates/valhall-storage" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
semver = { version = "1.0", features = ["serde"] }
thiserror = "1.0"
hashbrown = { version = "0.14.5", features = ["serde"] }
tracing = "0.1.40"
