[server]
ip = "0.0.0.0"
port = 3000

[storage]
type = "disk"
path = "storage"

[index]
git = true
sparse = true

[frontend]
assets_dir = "assets"
docs = { theme = "gray", auto-gen = true }
auth = ["email", "github", "gitlab"]
