[package]
name = "valhall-index"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
semver.workspace = true
thiserror.workspace = true
hashbrown.workspace = true
tracing.workspace = true
